apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/Josephmaclean/argocd-root-app
    targetRevision: HEAD
    path: resources/gateway-api
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
