apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-gp3-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Josephmaclean/argocd-root-app
    targetRevision: HEAD
    path: resources/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
