backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: postgresql.postgres.svc.cluster.local
    port: 5432
    database: mlflow
    user: postgres
    password: mlflow-temp-postgres-password

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::880145880830:role/private-eks-mlflow-role
  name: "mlflow-sa"

artifactRoot:
  s3:
    enabled: true
    bucket: private-eks-mlflow-artifacts

service:
  enabled: true
  type: ClusterIP
  port: 5000
  name: http
  containerPort: 5000
  containerPortName: mlflow

log:
  enabled: false
  # level: debug


extraArgs:
  uvicorn-opts: "--log-level debug"