backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: postgresql.postgres.svc.cluster.local
    port: 5432
    database: mlflow
    user: postgres
    password: mlflow-temp-postgres-password

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::880145880830:role/private-eks-mlflow-role
  name: "mlflow-sa"

artifactRoot:
  s3:
    enabled: true
    bucket: arn:aws:s3:::private-eks-mlflow-artifacts