architecture: standalone
fullnameOverride: postgresql

auth:
  database: mlflow
  postgresPassword: mlflow-temp-postgres-password

primary:
  persistence:
    enabled: true
    size: 10Gi
  initdb:
    scripts:
      create-litellm-db.sql: |
        SELECT 'CREATE DATABASE litellm' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'litellm')\gexec
